main: com.soraxus.clickhelp.SpigotClickHelp
name: SoraxusClickHelp
version: 1.0
author: Gravitinos
description: Help Plugin for Soraxus
commands:
  clickhelp:
    description: Help command
    usage: /<command>